### ISSUE TITLE
Autoreconnect Does Nothing?

### ISSUE THREAD

**Issue by xlxAciDxlx** [SaviorXTanren/mixer-client-csharp#29]
Is the `autoReconnect` flag in the connection something we're supposed to overwrite/do something with? Currently, it seems to do nothing. Seems like in the linked methods it's passed from the first connect, but it does nothing in the second.

&raquo; [ChatClient](https://github.com/SaviorXTanren/mixer-client-csharp/blob/master/Mixer.Base/Clients/ChatClient.cs#L83-L101)
&raquo; [ConstellationClient](https://github.com/SaviorXTanren/mixer-client-csharp/blob/master/Mixer.Base/Clients/ConstellationClient.cs#L165-L183)

**Comment by xlxAciDxlx** [comment]
> This variable is then referenced for when disconnection occurs to determine where to straight disconnect or disconnect then reconnect

Gotcha, I apparently didn't scroll down far enough :D Haha

A little bit of an aside, but would it be possible for me to "redirect" your Logger or capture it to log the way I do it? If not, would it be possible for you to add a log event so we can write a custom logger (or just generally log things our own way?)

Example:
```c#
Client.Log += Client_Log;

public void Log(String message)
{
    MyLogger.Log(message);
}
```

**Comment by SaviorXTanren** [comment]
There's an event to hook on to, it's the only way to get the logs:

https://github.com/SaviorXTanren/mixer-client-csharp/blob/master/Mixer.Base/Util/Logger.cs#L7-L16

**Comment by xlxAciDxlx** [comment]
So just doing `Logger.LogOccurred += MyLoggingHandler` should log to my method anytime you do a log call?

**Comment by SaviorXTanren** [comment]
Yep, that's how the event work as the code shows.

**Comment by xlxAciDxlx** [comment]
Doesn't seem to be working for me.

Event registration:
```c#
Mixer.Base.Util.Logger.LogOccurred += MixerBase_LogOccurred;
```

Method:
```c#
private void MixerBase_LogOccurred(Object sender, String message)
{
	this.Info("Logging from MixerBase..");
	this.Log(message, "MixerBase");
}
```

**Comment by SaviorXTanren** [comment]
> Nevermind, I think I'm just not reaching a point where you do any logging just by connecting.

There's only a few points where logging actually occurs (usually when an error occurs with websockets). So just cause you're not getting anything doesn't mean you missed it. Test it yourself by calling:

`Logger.Log("I'm a test message!");`

**Comment by xlxAciDxlx** [comment]
Logging works perfectly, thanks :D New issue though..

```txt
[03/28/2018 01:51:45PM] [Mixer API] [INFO] System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.WebSockets.ClientWebSocket'.
   at System.Net.WebSockets.ClientWebSocket.ThrowIfNotConnected()
   at System.Net.WebSockets.ClientWebSocket.CloseAsync(WebSocketCloseStatus closeStatus, String statusDescription, CancellationToken cancellationToken)
   at Mixer.Base.Web.WebSocketBase.Disconnect(WebSocketCloseStatus closeStatus)
```

**Comment by SaviorXTanren** [comment]
Not an issue, it's why there's a try-catch in there. WebSockets are very temperamental things, which is why it's one of the few areas I catch and don't throw exceptions, but still log them for diagnostic purposes.

**Comment by xlxAciDxlx** [comment]
> Not an issue

As in it shouldn't prevent reconnects, or it shouldn't break anything? It doesn't seem to be reconnecting.

**Comment by SaviorXTanren** [comment]
The second one is expected, attempting to get access to the web socket in our background thread can have some issues, those are not a concern.

As for the first one, this can happen sometimes if the object was disposed too quickly while reconnection is happening, but it should not be happening repeatedly. Are you still doing any manual re-connection in your code?

**Comment by xlxAciDxlx** [comment]
> Are you still doing any manual re-connection in your code?

I'm not. I wasn't sure if it would mess anything up. And given that reconnects are my biggest hurdle right now, I didn't want to chance it. Haha
