### ISSUE TITLE
Using a Client ID different to the sample projects causes an exception

### ISSUE THREAD

**Issue by cyberangel67** [SaviorXTanren/mixer-client-csharp#38]
I am not sure if I have done this right, but I created a project based on the sample code in this project, created a client id on my channel to register the App and when I try to connect I get an error at this line of code.

Am I missing something?

            this.connection = await MixerConnection.ConnectViaShortCode(clientID,
            new List<OAuthClientScopeEnum>()
            {
                OAuthClientScopeEnum.chat__chat,
                OAuthClientScopeEnum.chat__connect,
                OAuthClientScopeEnum.channel__details__self,
                OAuthClientScopeEnum.channel__update__self,
                OAuthClientScopeEnum.user__details__self,
                OAuthClientScopeEnum.user__log__self,
                OAuthClientScopeEnum.user__notification__self,
                OAuthClientScopeEnum.user__update__self,
            },
            (OAuthShortCodeModel code) =>
            {
                this.ShortCodeTextBox.Text = code.code;
                Process.Start("https://mixer.com/oauth/shortcode");
            });

**Comment by cyberangel67** [comment]
I should add, that if I use your client id, it works fine.

**Comment by SaviorXTanren** [comment]
Just to confirm a few things:

1) You created your OAuth client here? https://mixer.com/lab/oauth

2) You set the "Hosts" value on the OAuth client page to "localhost" if you're trying to do handle the OAuth authentication on the same computer you're requesting OAuth from:

![image](https://user-images.githubusercontent.com/752903/41697158-713c5ee6-74cc-11e8-9780-50d0ef84996c.png)

**Comment by cyberangel67** [comment]
That is what I did, however I did not do the website.

I added the google part and it makes no difference, if I use your ClientId it works fine. If I just use mine it crashes as soon as I hit the logon button, if I add the secretCode it at least allows me to go to adding the code and confirming it and then it crashes.

Always with a Bad Request.

**Comment by SaviorXTanren** [comment]
The google part isn't what matters, its the Hosts part. However, you're using shortcode authentication, so it shouldn't matter unless you decide to change to OAuth redirect.

I need more than just the type of the exception to understand what's going on. It should be throwing a RestServiceRequestException type, which will have a Reason & Content property. Please reply back with those so I can understand why the Bad Request is happening.

**Comment by cyberangel67** [comment]
Well it looks like the exception is not being caught, this is what I see in the IDE, if you need something more specific please let me know. The project is an exact copy of your repository code, except I changed the ClientID.

Exception.Content
 "{\"error\":\"invalid_client\"}" | string

StatusCode
BadRequest

StackTrace
"   at Mixer.Base.Services.RestServiceBase.<ProcessStringResponse>d__28.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() 
at Mixer.Base.Services.RestServiceBase.<ProcessResponse>d__26`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Mixer.Base.Services.RestServiceBase.<PostAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Mixer.Base.Services.OAuthService.<GetShortCode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Mixer.Base.MixerConnection.<ConnectViaShortCode>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
 at Mixer.Base.MixerConnection.<ConnectViaShortCode>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
at Mixer.LargeChat.WPF.MainWindow.<LoginButton_Click>d__9.MoveNext() in C:\\MixerChatBotTestWPF\\MainWindow.xaml.cs:line 61"

**Comment by SaviorXTanren** [comment]
Wait, did you check the "Use Secret Key" option when you created your application? If so, I believe you are required to specify that Secret Key as part of your authentication.

**Comment by cyberangel67** [comment]
There was no option for that and I said in the beginning I have tried that. The only difference in using that, is that I can then at least type in the authentication code, but it still crashes later with the same exception.

**Comment by SaviorXTanren** [comment]
If you have a client secret assigned to your OAuth application, then you need to to use it, it's a requirement of Mixer's OAuth. Otherwise, you need to create a new application and make sure that box isn't checked.

Does the later exception have the same Content value? A RestServiceRequestException is just anything that doesn't return a 200 OK response, so that doesn't mean it's the necessarily the same issue.

**Comment by cyberangel67** [comment]
Ok I now have it working.

I deleted the application from Mixer, which I had done once before. This time I removed the option for using the secret key in the program and didn't use it with the setting up of the Application and it works fine now.

It appears using the secret key with your library doesn't work.

**Comment by cyberangel67** [comment]
Why did you close this?

Using the secret key setup on Mixer and using it with your library throws an exception?

**Comment by SaviorXTanren** [comment]
Because I'm starting up issue to track this, I just need a few minutes to get all the information for the issue so I could create it.

Creating separate issue to track this more details - #41

**Comment by cyberangel67** [comment]
oh, then you might wish to close the new ticket i just created then
