### ISSUE TITLE
V2 Chatters API

### ISSUE THREAD

**Issue by mphacker** [SaviorXTanren/mixer-client-csharp#51]
I have been getting 503 errors from the Mixer V2 Chatters API from time to time when it loads a large number of chat users.  I think it is an issue with Mixer, but I wanted to mention it here in case there is some unexpected bug in the way the continuationToken is handled.

**Call:**
https://mixer.com/api/v2/chats/247596/users?continuationToken=eyJpZCI6bnVsbCwiY3QiOiJ7XCJ0b2tlblwiOlwiK1JJRDp3d0VBQU45MjZyV2M3WmNDQUFBQUFBPT0jUlQ6MyNUUkM6MTUwI1JURDpiUHBOUVZsSVJVMVRRVTVFVjBoSlEwZz0jRlBDOkFnSmFBR0VLV2dBQ0FNQ3NXd0FDQU1hRVh3QUVBTk9SUUpMYkJnSUFDS1hhQ0FJQXU3RU9DUUlBVmJ3VUNRUUF6NUtXaGhZSkFnREhyeG9KQWdBRnJSd0pBZ0JvaWxRSkFnQ3B0aW9LQWdBeW8wZ0tBZ0RuaUU4S0FnQlpxbFlLQWdCZHUxc0tBZ0FKc2x3S0FnQzhwbDRLSGdBTGlsaU9wNG05a0dPQXZZRkdnS2FBdllDbGdOYUFJb0J6Z0hXQ29JQmZDbklBSFlBemhyZUFUNENUZzVXQnZZRlRnc3lEaDRBUWdNRUZFQ0JkZ09XQ3BJRFNnVzZBR0lGVWdLeUFlWUhRZ3BDQWpJQkJndGlBT29Bd2dHT0FHWUFzZ0dTQkZZQUxnSnVBUW9Hd2dIeUFOb0IzZ0srQnJZQTBnYlNBcklGRWdmRUFoQUJhZ0JtQVdJQUJnTWVBTzRGd2dGdUFZQXJHQUJTRXNJQVBnUCtBRllDamdCT0F0SUlIZ2I2QTdZQUVnUzJBQm9CdWdiRUFBQVlhZ082QUxZRVRnQldBOTRCUGdDK0FHb0QxZ0NhQXFZRENnVjZBQ1lGTGcrRUFRUUEvZ1V1QVY0QVJnaG1CRTRFV2dhU0FrWUJQZ0pHQWxZQUJnaWlCSTRFM2dKdUFmb0RQZ05XQUNZQVNnRHFBWElBQWdWV0FINEF6Z1NTQURJQ1JnRktBTzRBWmdKcUFENEJsZ01hQU5vQWVnRUtBT0lCMGdSeUFHNEFuZ0FlQUZZQnpnRUtBdElBWGdKK0FjWUFSQUJBSWI0QlJnQnFBR0lEOGdLdUFSWUJ6Z0dFS3dnREdnRmlCTFlBUmdCR0FoWUJSQUlBUUc0QWVnQldBdllBR2dFT0FTNEFUZ0YyQVFvQmlnQVNCQ1lBWmdDdUFJSUR1Z0hHQU00QUtnRGFBS1lDR2dSQ0F0WUFlZ0hhQUs0QUpnQW1BTElEMmdGV0FTb0EzZ0ErQU5JQW1nQ0dCQklFaWdDT0FpSUFpZ0FTQVpJRWFnTVNBallCM2dDU0FBNEMrZ0RTQUtZQTdnQmlBZ1FDQUJCdUFJZ0JDQUVBQU1ZQVhnQjZBb1FCSUFDZUFESUFQZ0FIQXdBQjRnQktBSUlBTGdIeUFJNEJaZ0FTQU40QTZnR0VBQkFRcmdCU0FHSUFxZ0E9PVwiLFwicmFuZ2VcIjp7XCJtaW5cIjpcIlwiLFwibWF4XCI6XCIwNUMxQzlDRDY3MzM5OFwifX0ifQ%3D%3D

**Results:**
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>
  <head>
    <title>503 unable to get local issuer certificate</title>
  </head>
  <body>
    <h1>Error 503 unable to get local issuer certificate</h1>
    <p>unable to get local issuer certificate</p>
    <h3>Guru Mediation:</h3>
    <p>Details: cache-dfw18632-DFW 1545613854 444319134</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

**Stack Trace**
Mixer.Base.Util.RestServiceRequestException: unable to get local issuer certificate
   at Mixer.Base.Services.RestServiceBase.<ProcessStringResponse>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.RestServiceBase.<ProcessResponse>d__28`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.RestServiceBase.<GetPagedContinuationAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.ChatsService.ChatsV2Service.<GetUsers>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Mixer.Base.Services.ChatsService.<GetUsers>d__5.MoveNext()

**Comment by SaviorXTanren** [comment]
That looks like a Mixer related issue, but I doubt anything specifically having to do with the Chatters V2 API. I would assume this is something along the lines of their 503 first-byte timeout errors, something that's just going wonky on their back-end system.
